[docs] add logic to make latest release the default documentation

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -1,5 +1,6 @@
 SOURCEDIR = source
 BUILDDIR = build
+LATESTVER = $(shell git describe --tags --abbrev=0)
 
 # docs for all project versions will be placed here
 BUILDDIRALL = $(BUILDDIR)/allver/html
@@ -11,9 +12,8 @@ PY_SOURCE_EXCLUDE = $(shell cat source/.py_api_exclude)
 all: apidoc
 	sphinx-build -M html "$(SOURCEDIR)" "$(BUILDDIR)" -W --keep-going
 
-allver:
+allver: update-redirect
 	sphinx-multiversion "$(SOURCEDIR)" "$(BUILDDIRALL)"
-	cp source/_assets/redirect.html "$(BUILDDIRALL)/index.html"
 
 allver-info:
 	sphinx-multiversion --dump-metadata "$(SOURCEDIR)" "$(BUILDDIRALL)"
@@ -23,6 +23,14 @@ apidoc: clean-apidoc
 
 clean-apidoc:
 	rm -rf "$(SOURCEDIR)/generated"
+
+update-redirect:
+	branch=`cut -d. -f 1 <<< $(LATESTVER)`.`cut -d. -f 2 <<< $(LATESTVER)` && \
+    ln -fs "releases/$${branch}/index.html" "$(BUILDDIRALL)/index.html"
+	@if [ ! -f `readlink -f "$(BUILDDIRALL)/index.html"` ]; then \
+        echo "ERROR: could not determine valid documentation for the latest version"; \
+        exit 1; \
+    fi
 
 clean: clean-apidoc
 	rm -rf "$(BUILDDIR)"
