[docs] fix Makefile targets dependency

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -13,8 +13,14 @@ PY_SOURCE_EXCLUDE = $(shell cat source/.py_api_exclude)
 all: apidoc
 	sphinx-build -M html "$(SOURCEDIR)" "$(BUILDDIR)" -W --keep-going
 
-allver: update-redirect
+allver:
 	sphinx-multiversion "$(SOURCEDIR)" "$(BUILDDIRALL)"
+	branch=`cut -d. -f 1 <<< $(LATESTVER)`.`cut -d. -f 2 <<< $(LATESTVER)` && \
+    ln -fs "releases/$${branch}/index.html" "$(BUILDDIRALL)/index.html"
+	@if [ ! -f `readlink -f "$(BUILDDIRALL)/index.html"` ]; then \
+        echo "ERROR: could not determine valid documentation for the latest version"; \
+        exit 1; \
+    fi
 
 allver-info:
 	sphinx-multiversion --dump-metadata "$(SOURCEDIR)" "$(BUILDDIRALL)"
@@ -24,14 +30,6 @@ apidoc: clean-apidoc
 
 clean-apidoc:
 	rm -rf "$(SOURCEDIR)/generated"
-
-update-redirect:
-	branch=`cut -d. -f 1 <<< $(LATESTVER)`.`cut -d. -f 2 <<< $(LATESTVER)` && \
-    ln -fs "releases/$${branch}/index.html" "$(BUILDDIRALL)/index.html"
-	@if [ ! -f `readlink -f "$(BUILDDIRALL)/index.html"` ]; then \
-        echo "ERROR: could not determine valid documentation for the latest version"; \
-        exit 1; \
-    fi
 
 clean: clean-apidoc
 	rm -rf "$(BUILDDIR)"
